### ISSUE TITLE
Use semantic versioning?

### ISSUE THREAD

**Issue by agperson** [reset/libarchive-cookbook#7]
Since 0.5.0 is not backwards compatible as it (intentionally) breaks Chef 11 functionality, time to bump to 1.0.0?

**Comment by reset** [comment]
@agperson bumping from 0.4.x to 0.5.x is the correct change according to SemVer 2.0.0.

```
4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
```

```
8. Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.
```

The key here being X > 0 in section 8

**Comment by agperson** [comment]
Okie dokie, thanks.  In accordance with the SemVer FAQ that means this is not production ready and shouldn't be used by other cookbooks with version >= 1.0.0.  Disappointing.

**Comment by reset** [comment]
@agperson I actually don't think the doc says that at all. It does make mention about an API you want to remain consistent and respecting backwards compatibility. This software isn't 1.0 because of the exact issues that the 0.5.x release is attempting to fix - compile time race wars. This will be bumped to 1.0 once I have had enough success testing the 0.5.x release in my production environment.

**Comment by agperson** [comment]
Got it, thanks.
